# -*- coding: utf-8 -*-
"""Stage1_Screening_Normal_vs_Abnormal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXljbX_A8LEZaelKSHN6NJLVmx0NrVZS
"""

# CELL #1
from google.colab import drive
drive.mount('/content/drive')

# CELL #2
import os
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import timm

# CELL #3
PROJECT_ROOT = "/content/drive/MyDrive/BreastCancer_AI_Project"

CBIS_ROOT = PROJECT_ROOT + "/datasets/CBIS-DDSM"
BUSI_ROOT = PROJECT_ROOT + "/datasets/BUSI"

STAGE1_MODEL_DIR = PROJECT_ROOT + "/models/stage1"
os.makedirs(STAGE1_MODEL_DIR, exist_ok=True)

# CELL #4

# CBIS-DDSM
cbis_df = pd.read_csv(CBIS_ROOT + "/train_ready.csv")
cbis_df["stage1_label"] = 1  # all abnormal

# BUSI
busi_df = pd.read_csv(BUSI_ROOT + "/busi_train_ready.csv")

# BUSI mapping
busi_df["stage1_label"] = busi_df["label"].map({
    0: 0,  # normal
    1: 1,  # benign
    2: 1   # malignant
})

print("CBIS:", cbis_df.shape)
print("BUSI:", busi_df.shape)

# CELL #5

cbis_stage1 = cbis_df[["image_path", "stage1_label"]].copy()
cbis_stage1["root"] = CBIS_ROOT

busi_stage1 = busi_df[["image_path", "stage1_label"]].copy()
busi_stage1["root"] = BUSI_ROOT

stage1_df = pd.concat([cbis_stage1, busi_stage1]).reset_index(drop=True)

print(stage1_df.head())
print("Total Stage-1 samples:", len(stage1_df))

# CELL #6

class Stage1Dataset(Dataset):
    def __init__(self, df, transform):
        self.df = df
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(row.root, row.image_path)

        image = Image.open(img_path).convert("RGB")
        image = self.transform(image)

        label = torch.tensor(row.stage1_label, dtype=torch.long)
        return image, label

# CELL #7

tfms = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

# CELL #8

dataset = Stage1Dataset(stage1_df, tfms)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_ds, val_ds = torch.utils.data.random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=16)

# CELL #9

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = timm.create_model(
    "efficientnet_b0",
    pretrained=True,
    num_classes=2
).to(device)

# CELL #10

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# CELL #11

def train_epoch(loader):
    model.train()
    total_loss = 0

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

# CELL #12

def validate(loader):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            preds = outputs.argmax(dim=1)

            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return correct / total

# CELL #13

EPOCHS = 5

for epoch in range(EPOCHS):
    loss = train_epoch(train_loader)
    acc = validate(val_loader)
    print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {loss:.4f} | Val Acc: {acc:.4f}")

# Save Stage-1 model
torch.save(
    model.state_dict(),
    "/content/drive/MyDrive/BreastCancer_AI_Project/models/stage1/stage1_screening.pth"
)
print("Stage-1 model saved")

# SAVE STAGE-1 MODEL
torch.save(
    model.state_dict(),
    "/content/drive/MyDrive/BreastCancer_AI_Project/models/stage1/stage1_screening.pth"
)
print("✅ Stage-1 model saved permanently")